## Transforming Code into Idiomatic Python
* Replace traditional Index manupulation with Python core looping idiomatic

In [1]:
for i in [0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [2]:
for i in range(6):
    print(i**2,end=" ")

0 1 4 9 16 25 

## Looping over a collection

In [3]:
colors=['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")

red green yellow purple 

In [4]:
for color in colors:
    print(color,end=" ")

red green yellow purple 

## Looping backwards

In [5]:
colors=['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=' ')

purple yellow green red 

In [6]:
for color in reversed(colors):
    print(color,end=' ')

purple yellow green red 

## Looping in sorted list

In [7]:
colors=['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=' ')

yellow red purple green 

###
- if x<=y and y<=z:
- if x<=y<=z:
- if x==True:
- if x:

## Pandas

In [8]:
import pandas as pd


In [9]:
dt={'Id':[11,12,13,14,15],
   'first_name':['A','B','C','D','E'],
   'company':['aa','bb','cc','dd','ee'],
   'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt=pd.DataFrame(dt)

In [24]:
print(mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [25]:
import os

In [26]:
os.chdir("PathFile")

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'PathFile'

In [27]:
mydt.to_csv('WorkingFile.csv',index=False)

### Reading the data from csv file

In [29]:
mydata=pd.read_csv('WorkingFile.csv')

In [30]:
print(mydata)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [31]:
mydata1=pd.read_csv('WorkingFile.csv',skiprows=[1,2,3],
                   names=["CustId","Name","Company","Address"])

In [32]:
print(mydata1)

  CustId        Name  Company  Address
0     Id  first_name  company  address
1     14           D       dd      Hyd
2     15           E       ee      Hyd


In [33]:
pwd

'C:\\Users\\Rohith\\Python'

### print only two columns
### print the large value from custid column max
### least value
### average

In [37]:
mydata1=pd.read_csv('WorkingFile.csv',skip=[1,2,3])

TypeError: parser_f() got an unexpected keyword argument 'skip'

In [38]:
d={'first_name':['A','B','C','D','E'],
'CustId':[11,12,13,14,15]}
myData = pd.DataFrame(d)  
print(myData)
CustId=[11,12,13,14,15]
print("Max of Customer Id:",max(CustId))
print("Min of Customer Id:",min(CustId))
print("Average of Customer Id:",sum(CustId)/len(CustId))


  first_name  CustId
0          A      11
1          B      12
2          C      13
3          D      14
4          E      15
Max of Customer Id: 15
Min of Customer Id: 11
Average of Customer Id: 13.0


## Numpy -working with multidimensional array
- a bit like python
- Numpy array is data structure of numpy Lib
- Numpy short name for 'Numeric Python'

In [46]:
import numpy as np

In [47]:
li=[1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [48]:
array=np.array(li)
print(array)

[1 2 3 4 5]


In [49]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [51]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
